[Desktop]
WallpaperMode=stretch
Wallpaper=/usr/share/opsec/wallpaper.png
WallpaperCommon=0
ShowHidden=0
ShowDocuments=0
ShowTrash=1
ShowMounts=0
Folder=~/Desktop
IconSize=48
SingleClick=0
Font=Noto Sans 10
ShowWmMenu=1
ShowTooltips=1
DeskTopItemShowBig=0

[ui]
AlwaysShowTab=0
CloseOnUnmount=1
LastWindowWidth=800
LastWindowHeight=600
ShowTabClose=1
ShowTabCloseMouseMiddle=1

[fm]
AllowReordering=1
SearchRecursive=1
ShowBookmarks=1
ShowHidden=0
ShowIconEmblems=1
ShowMenuBar=0
ShowSidebar=1
ShowStatusbar=1
ShowToolbar=1
SortHiddenLast=1

[system]
AddTrashToDesktop=0
AddHomeToDesktop=0
